"""add delivery core

Revision ID: 5231e1da81f0
Revises: 42ac6497d3a4
Create Date: 2026-02-06 14:21:10.974597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5231e1da81f0'
down_revision: Union[str, Sequence[str], None] = '42ac6497d3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mvp_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_value', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ready', 'in_progress', 'done', name='featurestatus'), nullable=True),
    sa.ForeignKeyConstraint(['mvp_id'], ['mvps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('estimate', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'doing', 'done', name='storystatus'), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stories')
    op.drop_table('features')
    # ### end Alembic commands ###
